### ISSUE TITLE
Question about LSTM bp

### ISSUE THREAD

**Issue by kli-casia** [arunmallya/arunmallya.github.io#3]
![qq 20161129210749](https://cloud.githubusercontent.com/assets/13194870/20710951/fe2992ca-b677-11e6-8ae2-944b2c71dc90.jpg)

Could you explain the meaning of += in detail?

You said that 
```
+= above is so that this gradient is added to gradient from time step (t+1) (calculated on next slide)
```
But there is no gradient from time step t+1 calculated on the next slide...
Thank you very much.

**Comment by arunmallya** [comment]
Consider t = T (some constant, say 10). 
c^10 gets an update as noted in http://arunmallya.github.io/writeups/nn/lstm/index.html#/6
Previously (we are backpropagating, going reverse in time), for t = 11, c^{t-1} = c^{11-1} = c^10 has some gradient as computed in bottom-right equation of http://arunmallya.github.io/writeups/nn/lstm/index.html#/7
Thus, c^10 receives two gradient values, one at T = 11 and one at T = 10, both of which are to be added to each other, not overwritten (gradients are accumulated). Thus the +=.

**Comment by kli-casia** [comment]
Thank you very much.  Your answer helped me a lot.
