### ISSUE TITLE
Website not displayed correctly

### ISSUE THREAD

**Issue by georgeblck** [arunmallya/arunmallya.github.io#4]
First of all: thank you for your writeups on Backprop in general and the LSTM backprop. It has been a huge help!
I have a problem with your post on LSTM-backprop not being displayed correctly. Right now I am on a Windows7 computer with Firefox, but it has the same problem on different browsers in Linux (Chrome, Firefox):

![gitio](https://cloud.githubusercontent.com/assets/6574368/23017007/dee4e7ee-f438-11e6-863e-f3fda616c698.png)

As you can see, the most interesting part - the equations - are always cut of. One can zoom out to 50%-60% but then the equations get quite small.

**Comment by arunmallya** [comment]
Hi, sorry about the late reply, didn't get a notification for some reason.
Do you have a js blocker on? This seems to render properly on my linux and mac machines.

Also, is your screen size weird? I use the wonderful http://lab.hakim.se/reveal-js/#/ package for my slides and it might have some expected screen size hardcoded inside, though I suspect that's the case.

**Comment by georgeblck** [comment]
Hi, thanks for your answer!
You were right; I am currently able to view it correctly on Windows with Firefox without add-ons.

I will also check my screen size.
