### ISSUE TITLE
LSTM Backward Pass Question

### ISSUE THREAD

**Issue by kli-casia** [arunmallya/arunmallya.github.io#5]
![qq 20170415144527](https://cloud.githubusercontent.com/assets/13194870/25061541/57f79908-21eb-11e7-8f4f-ee6a182eac5a.jpg)

I don't understand the equation in the red box.

---------------------------------------------------------------
![qq 20170415144610](https://cloud.githubusercontent.com/assets/13194870/25061524/0cbc0050-21eb-11e7-8d15-6284513f0d5b.jpg)
![qq 20170415144621](https://cloud.githubusercontent.com/assets/13194870/25061525/0cbd1d5a-21eb-11e7-9464-b8225e01e64b.jpg)
In my opinion, f^t is also indirectly depend on c^(t-1), since f^t is depend on h^(t-1), and h^(t-1) is depend on c^(t-1). What's more, i^t and a^t are also indirectly depend on c^(t-1) for the same reason.

------------------------------------------------------
![qq 20170415145303](https://cloud.githubusercontent.com/assets/13194870/25061536/3dbd0456-21eb-11e7-9053-0b8859d8108f.jpg)
So I think the above equation may not be correct?

Am I right?

Thank you very much!

**Comment by arunmallya** [comment]
Basically uses an application of BPTT: https://en.wikipedia.org/wiki/Backpropagation_through_time
