### ISSUE TITLE
LSTM backpropagation

### ISSUE THREAD

**Issue by mxlei01** [arunmallya/arunmallya.github.io#6]
Hi, 

in the equations noted in: [http://arunmallya.github.io/writeups/nn/lstm/index.html#/10](url)

For the derivative of i^hat, I think you took the derivative of sigmoid, but why isn't there any sigmoid function? Is there an error?

Thanks

**Comment by arunmallya** [comment]
Note that `i^t = \sigma(\hat{i}^t)` (http://arunmallya.github.io/writeups/nn/lstm/index.html#/2) is after a sigmoid. 
Derivative of `y=\sigma(x)` wrt `x` is `y(1-y)`.
Thus, derivative of `\hat{i}^t` is `i^t(1-i^t)`, as in http://arunmallya.github.io/writeups/nn/lstm/index.html#/10
